### ISSUE TITLE
[feature] Be able to de-escalate an item

### ISSUE THREAD

**Issue by j-barnak** [NiloCK/tuido#1]
Unless I'm missing something in the docs, I'm unsure if I could de-escalate an item (remove the `!` from the item).  Perhaps `;` could be the syntax for de-escalating?

**Comment by NiloCK** [comment]
You are not missing anything. I felt like any action directly opposite some other action ought to have a the same keystroke, but with a modifier key. Goal being to minimize total cognitive load for learning the (already fairly large) list of keystrokes.

So I got stuck on a keystroke for de-escalation given that exclamation points already involve the `shift` "modifier". Considered `1`, `ctrl`-`shift`-`1` (`ctrl`-`!`), etc. `;` has some resemblance to an exclamation mark, so maybe it fits?

In the meantime, `e`-`home`-`del`-`del`-... is a pretty quick workflow for pruning leading exclamations.
