### ISSUE TITLE
Add ignore folders

### ISSUE THREAD

**Issue by kevin-gwyrdh** [NiloCK/tuido#22]
Hello 

Thanks again for this! 

Another thought is there a way to add folders to ignore? Use case would be I have projects templates which come with task lists prepopulated. Currently these templates sit in a sub folder of my main project folder. These "template tasks" are being picked up by tuido. I could move the template folder out of the project folder however it would be really helpful to be able to add "ignore folders called template" to the config in a similar way you can add / remove file types. I can't find the place to hack this!!

Enjoying trialling this.

**Comment by kevin-gwyrdh** [comment]
btw tried .gitignore file in the project folder but no results with either including either the template folder or a specified file.

**Comment by NiloCK** [comment]
This is a little surprising because, from top-of-head, the tree traversal ought to respect `.gitignore` files already.

Will have a look soon.

Rough ETA on both issues is ~2-4 days.

**Comment by NiloCK** [comment]
@kevin-gwyrdh This ought to be fixed now in the 0.0.10 release. Fixed as in: using a `.gitignore` file should now work.

Let me know if that isn't the case and I'll reopen.

**Comment by kevin-gwyrdh** [comment]
Thanks speedy :-) I'll be able to check at the weekend

**Comment by kevin-gwyrdh** [comment]
Quick checks and all seems to be working. Thanks!
