### ISSUE TITLE
Duplicate entries for a user defined directory

### ISSUE THREAD

**Issue by sprek** [NiloCK/tuido#6]
Hello. I love the project, but I had some issues when I was trying to incorporate it into my workflow.

I edited the .tuido file, removed "go" from the extensions, and changed writeto to be the full path to my own notes folder. This notes folder only contains a single .md file right now.

When I run the program, it loads the notes from the file, but each entry is duplicated. So my original file that contains:
[ ] Task 1
[ ] Task 2

In the tuido interface it looks like:
[ ] Task 1
[ ] Task 2
[ ] Task 1
[ ] Task 2

**Comment by NiloCK** [comment]
Hi @sprek.

Bit of a late reply!

I didn't reproduce this bug locally, but I'm fairly confident that it would have been fixed with [this commit](https://github.com/NiloCK/tuido/commit/4387d315630804718fcc5d7c78a83220026438ea).

The current `0.0.6` release should not have this issue.
